<section>
<div class="container user_agreement">
<div class="row">
<div class="col-md-12"><h1>FULL RISK DISCLOSURE, DISCLAIMER AND USER AGREEMENT</h1></div>
</div>
<div class="row">
<p><strong>Refunds: </strong></p>
<p>If you purchase one of our products, after your payment has cleared your license to use the software will be activated. Once the license is activated, no refunds will be given. We have this policy since it would be impossible for you to return your registered version of our software.</p>
<p><strong>Risk Disclosure Statement</strong></p>
<p> Risks involved in active trading can be substantial. You should, therefore, carefully consider whether such trading is suitable for you in light of your circumstances and financial resources. You should be aware of the following points:</p>
<ol>
    <li>You may sustain a total loss of the funds that you deposit with your broker to establish or maintain a position in the market, and you may incur losses beyond these amounts. If the market moves against your position, you may be called upon by your broker to deposit a substantial amount of additional margin funds, on short notice, in order to maintain your position. If you do not provide the required funds within the time required by your broker, your position may be liquidated at a loss, and you will be liable for any resulting deficit in your account.</li>
    <li>Placing contingent orders, such as “stop-loss” or “stop-limit” orders, will not necessarily limit your losses to the intended amounts, since market conditions on the exchange where the order is placed may make it impossible to execute such orders.</li>
    <li>All futures positions involve risk, and a “spread” position may not be less risky than an outright “long” or “short” position.</li>
    <li>The high degree of leverage (gearing) that is often obtainable in futures trading because of the small margin requirements can work against you as well as for you. Leverage (gearing) can lead to large losses as well as gains.</li>
    <li>You should consult your broker concerning the nature of the protections available to safeguard funds or property deposited for your account.</li>
    <li>ALL OF THE POINTS NOTED ABOVE APPLY TO ALL FUTURES TRADING WHETHER FOREIGN OR DOMESTIC. IN ADDITION, IF YOU ARE CONTEMPLATING TRADING FOREIGN FUTURES OR OPTIONS CONTRACTS, YOU SHOULD BE AWARE OF THE FOLLOWING ADDITIONAL RISKS:</li>
    <li>Foreign futures transactions involve executing and clearing trades on a foreign exchange. This is the case even if the foreign exchange is formally “linked” to a domestic exchange, whereby a trade executed on one exchange liquidates or establishes a position on the other exchange. No domestic organization regulates the activities of a foreign exchange, including the execution, delivery, and clearing of transactions on such an exchange, and no domestic regulator has the power to compel enforcement of the rules of the foreign exchange or the laws of the foreign country. Moreover, such laws or regulations will vary depending on the foreign country in which the transaction occurs. For these reasons, customers who trade on foreign exchanges may not be afforded certain of the protections which apply to domestic transactions, including the right to use domestic alternative dispute resolution procedures. In particular, funds received from customers to margin foreign futures transactions may not be provided the same protections as funds received to margin futures transactions on domestic exchanges. Before you trade, you should familiarize yourself with the foreign rules which will apply to your particular transaction.</li>
    <li>Finally, you should be aware that the price of any foreign futures or option contract and, therefore, the potential profit and loss resulting therefrom, may be affected by any fluctuation in the foreign exchange rate between the time the order is placed and the foreign futures contract is liquidated or the foreign option contract is liquidated or exercised.</li>
</ol>
<p>Hypothetical performance results have many inherent limitations, some of which are described below. No representation is being made that any account will or is likely to achieve profits or losses similar to those shown. In fact, there are frequently sharp differences between hypothetical performance results and the actual results subsequently achieved by any particular trading program.</p>
<p>One of the limitations of hypothetical performance results is that they are generally prepared with the benefit of hindsight. In addition, hypothetical trading does not involve financial risk, and no hypothetical trading record can completely account for the impact of financial risk in actual trading. For example, the ability to withstand losses or to adhere to a particular trading program in spite of trading losses are material points which can also adversely affect actual trading results. There are numerous other factors related to the markets in general or to the implementation of any specific trading program which cannot be fully accounted for in the preparation of hypothetical performance results and all of which can adversely affect actual trading results.</p>
<p>Past performance is not indicative of future results.</p>
<p>Futures, options of futures, stocks, forex and options involve substantial risk and are not suitable for all investors.</p>
<P>All testimonials from students and graduates of our courses or who use our tools and resources are believed to be true based on representations of the persons providing the testimonials, but facts stated in testimonials have not been independently audited or verified. Nor have there been any attempt to determine whether any testimonials are representative of the experiences of all persons using the methods described herein or to compare the experiences of the persons giving the testimonials after the testimonials were given. The average reader should not necessarily expect the same or similar results. Past performance is not necessarily indicative of future results. No person was compensated for providing a testimonial.</P>
</div>
</div>
</section>