<section class="banner_sec_about about_bg">
            <div class="container">
                <div class="row">
                    <div class="banner_text1">
                        <h1 style="color: white;" class="market_banner">ONE AND ONE MENTORING WITH JOHN</h1>
                    </div>
                </div>
            </div>
        </section>

    <section>
        <div class="container bottom_div">
           
                <div class="row">
                    <div class="col-4"></div>
                    <div class="col-4"><h1 class="cot_heading mentoring_heading">COT Reports</h1></div>
                    <div class="col-4"></div>

</div>
<p>COT Report Introduction:</p>
<p>One technique to gauge the consensus is to use the Commodity Futures Trading Commission’s (CFTC) Commitment- of- traders (COT) report to help analyze the market. It is a report that reveals whose doing what or whose hands the market is in. Many investors who have trade stocks and who have never traded Futures think of it as like “insider trading”. Well, not exactly. This report breaks down the three main categories of traders and shows their overall net positions. The first group is called the Commercials or hedgers, the next group is called the Large Speculators and the third group is called the Small Speculators. It is known that the Commercials and the Large Traders have large positions and as a rule when you trade a certain number of contracts these positions need to be reported to the CFTC. The number of allowable positions that need to be reported varies by different futures contracts. If you compile the data and subtract these figures from the total open Interest that is provided by the exchanges then the balance is assumed to be from the small speculators.</p>
<p><a target="_blank" href="https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm">GET REPORT</a></p>
<p>The data is taken from the close of business on Tuesday and then released on the following Friday at 2:30 PM CST for Futures only. It is also released twice a month or every other Monday for futures combined with the figures for options.</p>
<p>One fact that you need to remember is that commodities are listed by the exchanges they are traded at. Therefore you will need to know what commodity is traded on which exchange. The Dow Jones Industrial Average futures contract is traded at the Chicago Board of Trade, so to access the report every week, type in this address above in your browser, then scroll down until you see Chicago Board of Trade and then click on the SHORT FORM. Then you will see every commodity traded on that exchange and you simply scroll down until you find the market you wish to view the information for.</p>
<p>In order to understand the importance of the COT report, it helps to know what the break down of the numbers are and what they represent. The Commercials are considered to be hedgers as I mentioned. They could be Producers or Users of a given product. Due to the fact that they will or do own the underlying product they are trying to hedge their risk in the cash market from adverse price moves. They do this in the futures market and they generally receive a discount from the Margin requirements set for speculators. When a commercial entity fills out their account application they usually disclose that they are hedging. The exchanges recognize that hedgers are on the other side of the market from a cash standpoint and can usually financially speaking support their futures position, therefore they set lower Margin rates for those accounts. Commercials are considered to be the “smart money” or the strong hands because they are in the business of that commodity.</p>
<p>They are considered to have the “inside scoop” sort to speak. For example, from having access to internal corporate inventory reports to global production estimates and projected customer needs, commercials have a better working knowledge of the fundamentals. Another example would be for Banks and Institutions, they may have a better idea on the direction of money supply and corporate debt for instance and may want to hedge their exposure on current holdings against an upcoming adjustment in Interest Rates. For the most part they are using the futures markets to lock in prices to produce a profit or lower their costs on the cash side of their positions.</p>
<p>The Large Traders category is considered to be the professional trader. The Commodity Trading Advisor or the Commodity Pool Operator who manages a large fund is considered to be a large trader if they hold a certain amount of positions. It may also be an individual trader who holds a substantial position in the market.
<br>Traders that have positions over a certain amount of contracts need to disclose those positions to the CFTC. Each futures contract has a different number for it’s reportable limits and just like Margins and can change on a moment’s notice.</p>
<p>The theory is if you are a large trader you are committing a large amount of capital to a risky investment and have confidence in that position. You are either a very good trader that started small and built your capital up or you are a professional trader with a good track record. Either way you look at it professional traders with large reportable position limits on are still speculating in the markets with the motive for profit. They are well financed and typically have large amounts of money to defend their positions.</p>
<p>The last group is called the Small Traders or speculators. These are regular investors, mainly the general trading public doing it on their own or using the advice from an advisory newsletter service or a broker or a combination of all three. Since it is estimated that 80% or more of traders who enter the markets lose, this is the category that one generally does not want to usually follow. Remember that nothing is a 100 % iron clad guarantee in this business.</p>
<p>There is a couple of old phrases that may explain why. First even a blind squirrel can find an acorn and a broken clock is always right twice a day. Even the little guys win once in a while. I have found that a lot of individual investors have a good knack for calling market direction but have a hard time with timing when it comes to entering or exiting the market. The problem is they are usually under-capitalized in the market and cannot defend their positions during periods of volatility. One other scenario is they sometimes refuse to take a profit when the market gives it to them. Due to the very nature of the markets moves some novice traders invest with a buy and hold mentality. For that reason the sheer psychology and emotional makeup of individual investors needs to be addressed before investing in the futures and options market. For some investors managing risk is not as hard as managing a winning trade. Again there are many variables why the individual speculator is often wrong in the markets and looses money. My concern here is that you realize who represents what when it comes to the C.F.T.C Commitment of Traders report.</p>
<p>It is also important to understand and to watch the behavior of the market from Tuesday to Fridays close. This can change the interpretation of the numbers as the market participants have had a chance to adjust their positions as the report can lose its importance if market conditions have changed during that time period. What you want to watch for is the net positions for each category and if you see a lop-sided market position and prices are at an extreme high or an extreme low this could signal a major turn around in price direction.</p>
<p>Here is an example of what to watch for, if the large traders are net long, the commercials are net short, the Small Speculators are extremely long from a historical perspective or a large percentage amount from an open interest basis. Then to add to this scenario if the market is at an extreme high or has been steadily rising for a good period of time look out, a downside correction could be around the corner. You see, once the data is released, it is like trying to run ahead of an avalanche, everyone is headed for the exit door and nobody wants to be last. At least from the large traders or non commercial category perspective. If they see that the market is vulnerable for a price correction all it takes is a few smart traders to start liquidating long positions and a sharp sell-off could begin. It is important to view the Commitment of traders report to see whose “hands” the market is in. Look for the report every Friday and every other Monday for the futures and options figures combined.</p>
<p>Let’s put this theory to the test and examine a recent situation in the Dow Jones Futures contract. The Table below shows the three categories, Non- commercials (large professional speculators) Commercials (banks and institutions hedging risk) Non-reportable positions (small individual speculators).</p>
<p>As the data shows above, the Dow had the Non-reportable position category or the small speculators (general public) short by 45,790 contracts versus long 15,360, that makes a net short position of 30,430 contracts. The large non-commercial category or professional speculators were long 43,227 versus short 64,402 or a total net short position of 21,175 contracts. This means that professionals were short but not as many contracts and most likely this category of professional traders are more likely to react faster to market changes and they tend to get out of positions at better prices than small speculators. Generally speaking non-professional traders lack discipline and hold onto positions longer and are more likely to take winners into losers.</p>
<p>The chart below highlights the markets condition as of the date of the report and as you can see, when too many speculators are in a large position, we can expect price reversals. Over the long term they might be right but more times than not small speculators lose so we want to be careful not to follow the herd mentality. Certainly one would not want to start selling short on the close on Friday of March 16th, 2007 as you would have had access to the CFTC report showing a big net short position of small speculators, especially after the stock market had a three week price decline of almost 6%!</p>
<p>As the chart below shows, the following Monday the market rallied reversing some losses and as a result anyone left short was now either giving back profits or worse, losing money.</p>
<p>It is often said that timing is everything and using the CFTC report may help you in that sense. As with any form o analysis nothing can guarantee profits but this report reflects the facts of whose hands the market is in control. If the small speculators are usually wrong then by finding out if they are in a large position or betting the market will go one way, then you might want to wait or simply get out before joining them and end up on the wrong side of the market. The best thing about this report is it is considered as a legal and legitimate way of getting “insider” information.</p>
<p>Regards and Good Trading,</p>
<p>John L Person, CTA</p>
</div>
</section>