<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>  
<script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
  
  <div id="test-list" class="container">
  
    <ul class="list">
        <hr>
      <p class="name">Hi John, I would like to thank you for your last trade on the oil that U mentioned last week. The call option that you suggest to buy (USO) worked just perfect. Have a great trading week.</p><hr>
      <p class="name">My name is Kris and I attended the presentation that John gave to the trading group that I was part of last saturday. I would like to say thank you to John for how much he has helped me and my father become better traders. Listening to him and learning about his system has actually helped us understand more of …</p><hr>
      <p class="name">Hi John, I wanted to let you know that I announced in the room today that with the trade we took this morning I officially paid for my investment in TTU. I started right after the July 4th Holiday. This was one of my first major goals I had set for myself and wanted to share it with you</p><hr>
      <p class="name">Thank you John! I really cannot overstate how valuable your work will be to me, and I am very grateful to see this great work provided in TOS. Since your original presentation, I back tested against many, many stocks I am trading and it really is very predictive as you already know but I am just discovering in my areas …</p><hr>
      <p class="name">This is not the first time writing to you expressing gratitude. It was light in FOREX trading that i have seen after reading your book FOREX Conquered. Your words are now carved iny my brain, and i remeber them before every trade. Today March 1, 2010 i collected 329 pips out of possible 395 pips shorting the sterling pound. Thanks …</p><hr>
      <p class="name">I have been doing great with your system. this is making my retirement plans pan out extremely well. your system is fantastic. thank you so much</p><hr>
      <p class="name">Hi John, Friday the 13th or not you conducted a excellent seminar (closely approaching fabulous!). Any time someone can take the time to give back and help others accomplish that which he or she has learned and profited from it’s not only rare, but very admirable, so thank you!! I appreciate and thank you for your patience as I believe …</p><hr>
      <p class="name">John Person John, I have just completed the instructional videos and they were very helpful. they are very well done. Yesterday Mary had my data feed turned on and today in the yen I have made over 3000.00 dollars. To say the least i’m excited. Thank you</p><hr>
      <p class="name">Dear Mr. Person, I’ve been a retail commodity broker for 10 years now, this absolutely is the best book I’ve ever read on trading. I am on my third read of this book. I need to attend your seminar so I can learn more! When is the next one and do you plan to come to Chicago this year? Thanks for everything!!!!!!!!!</p><hr>
      <p class="name">Dear John, After recently reading your book Candlestick and Pivot Point Trading Triggers and applying your method to trading the Dutch stock index future contract (AEX “Future” FTI ) I?m pleased to inform you, that it works here too! Regards</p><hr>
      <p class="name">John: Este mensaje lo voy a escribir en Español, tengo el curso de Trading Triggers y el de Forex Conquered….a partir de que empecé a estudiar estos cursos mi trading ha evolucionado impresionantemente, ya tengo record ganador. No solo puedo hablar de uno, dos, tres trades en especial, sabemos que esto no funciona así, sino que en términos generales mis …</p><hr>
      <p class="name">Hi John, I’ve recently purchased your “Trading Triggers…The Secrets To Profitable Trading”… ….So far, I find your course very helpful and after following Steve Nison’s course on candlesticks, not once during the two years has he made mention of anything remotely close to the “Failed Doji Top”…though I’ve learned quite a bit from Mr Nison and others such as Toni …</p><hr>
      <p class="name">I attended an introductory lecture at the Wealth Expo in Anaheim back in March. Though I listened to you with caution, I could not wait to get in front of my monitor to put your trading set ups to test. The very next day, I traded the signals, and sure enough they worked. I took that profit and rushed to …</p><hr>
      <p class="name">John:I have been trading stocks and options for years. I really never had much success trading options. Though I had sizable wins in the equities market during the bull run , I would end up giving a good portion of the profits back on market reversal. Frustrated with the equities and the options market, I started trading the emini S&P. …</p><hr>
      <p class="name">I have been out of the course for two weeks. I have not had a losing day. I now trade a 100% better, I trade with less fear, with more confidence and stay on profit course rather than getting out prematurely. I don’t? over trade. I stopped foolish trading and wishful thinking on losing trades. I accept small losses [ …</p><hr>
      <p class="name">Hello John, I am a subscriber to your Live trading Room hosted by Butch Heading and have been trading the E-min S&P\’s for the last 5 years, 2 years professionally. I have been successful as a trader using Pivots and a Momentum signal approach, however since I have been applying your methods of reading candle sticks as well as your …</p><hr>
      <p class="name">Thanks for your speedy and courteous response. I stand by my original comments that your organization is first class and I would recommend you to any trader that is interested in learning how to trade consistently and successfully. What I learned from the trading room and working with the tools that John created has made a very positive change in …</p><hr>
      <p class="name">John, I’m a TOS client who uses your PPS Indicator with Forex Trading. Over the last 180 trading days using the PPS I have a 74% win rate. I just wanted to thank you for this indicator. Sincerly, Greg J.</p><hr>
      <p class="name">Just finished watching John’s presentation ( yes, too many Seinfeld reruns ) and as I sat there I found myself going from half watching/listening intermixed with a little channel surfing to singular focus.  I don’t think I’ve ever said to myself “I’ll be damned” as much I just did in that presentation. That was an eye opener.  Please put me …</p><hr>
      <p class="name">Hi Mary, I also really appreciate John’s analysis. I am interested in his futures newsletter.</p><hr>
      <p class="name">I would like to add that John Person’s lucid analysis of the markets is on par with Larry W. on market forecasting. Way to go! And keep sending invitations.</p><hr>
      <p class="name">That was a really good presentation. I have been playing with all the new indicators all morning. Now to trade with them….Thanks!</p><hr>
      <p class="name">Hi Mary, Thanks for sharing, and for the recording link. I met John at the Trader’s Expo in las Vegas years ago and have been a big fan and promoter of him ever since. I was so impressed that he took the time after his presentation to speak with me and that his philosophies were very logical and in line …</p><hr>
      <p class="name">Thank you for all the trader’s help you are providing. Best, Ren</p><hr>
      <p class="name">Hello Mary, Excellent webinar about moving averages. It is the first time that I have listen such a detailed explanation on averages. Thank you</p><hr>
      <p class="name">Hi John, I want to thank you for the time you take when you provide terrific information like the Sector line chart you showed me this morning. I have reconstructed that chart and have included the GLD ETF also. It will be very useful in the future looking at which sectors are about to breakout and which one to stay …</p><hr>
      <p class="name">Hello John,   I had the pleasure in meeting you in Toronto back in October of 2012, you signed my book even with your hand inoperable. I hope you have healed well. I would  like to thank you once again as your monthly pivots strategy has worked time in, and time out for me. I have now had 11 successive profitable trades, …</p><hr>
      <p class="name">…I’m still benefitting from your Trading Triggers course, and 3 of your books in which one book, I was fortunate enough to have autographed while you were in Toronto last year in October. To date, my favourite John Person tactics are, the high and low close doji, the Benchmark candle, and congruency of either pivots, Fibonacci and Ma’s. Plus, calculating and …</p><hr>
      <p class="name">Eduardo G.G: john sorry to bother you but just wanted to tell you that using your snap back method i entered long on the 60 min chart with one contract, bought two more on the breakout of the candle that gave the signal, then got out of two contracts at previous highs with a profit of 312.5 and now riding …</p><hr>
      <p class="name">…And  as a new person using  TOS (6 years with TS) I am so looking forward to your seasonality program that will be coming on the TOS platform. I remember seeing you at Trader’s Library Show a few years ago and was looking forward to seeing you again with a few more years of experience behind me. I was NOT …</p><hr>
      <p class="name">I attended the show at McCormick here in Chicago on Friday.  You were definitely one of the top speakers. Being new to Options trading I am trying to learn as much as possible on top strategies to be able to do this full-time.  I have a passion for the market, watch it all day, but have always been in stocks. …</p><hr>    
      <p class="name">Hi John, When I had met you in San Jose few months back, you had told me gold will go down to $1300 – how right you were! I listened to you and did not buy any – you saved me a ton of money – thank you so much!!!…GP</p><hr> 
      <p class="name">Hi John- My sincerest thanks and gratitude to you for your presentation last night.  You were an amazing, dynamic, speaker and offered significant content–much of which, I think, was new and very relevant to the members. It was truly an A+ event!! Hope you will accept another invitation in the future to speak to us again…..Gratefully, Amy K</p><hr> 
      <p class="name">Hello Mary, I hope you had fun at the golf event.  Tell John he was right on the money (pun intended).  I think John was in the minority of seeing the signs that the market would continue up, and despite all the other analysts that were convinced it was going to turn down.  John nailed it as usual!  Tell him, …</p><hr> 
      <p class="name">You can day trade the way you are running the room.  I have had the best qtr of trading this year.  Don R.</p><hr> 
      <p class="name">John Tks for your mentoring Class in N. Palm Beach.  I followed you slass on option and was able to B a 235 Jun Apple call last Friday. It Gapped up this AM with almost $500.00 profit on I contract Ed L.</p><hr> 
      <p class="name">Dear John and Mary, Thank you for putting together a first class cruise. We throughly enjoyed everything. The review of your system with emphasis on how to be more effective has been great for us.. The mentoring at sea was planned and executed extremely well. The schedule was adhered to and also allowed plenty of relaxation and family time. We …</p><hr> 
      <p class="name">Hi Mary and John, what an absolutely superb time we had on the cruise. It was everything we had hoped it would be for us and more.</p><hr> 
      <p class="name">Hello Mary, I have been following John Person since early 2010.  Over the years, I have studied many market professionals, but have found none to be of the same caliber as John. John is a consummate professional who is happy to share his knowledge with those willing to put forward the effort to learn trading through his teachings. Some of …</p><hr> 
      <p class="name">Please thank John for that amazing analysis of the USO option trade is last nights stock report. Pro at work for sure. cheers, Michael</p><hr> 
      <p class="name">Dear John and Mary, …Personally, I started trading full time about a year ago. Up until that point, my own market involvement was limited to longer term holdings because I had been told by the …… that trading was a sucker’s game…and I believed them. However, as time went on, I became so infatuated with the markets, active trading was …</p><hr> 
      <p class="name">Thank you John!  Thank you for making the journey to Kansas City (Overland Park, Kansas) and for your terrific presentation on Saturday morning</p><hr> 
      <p class="name">happy easter to the Person family. Thanks for all the training I have gotten from you over the years, even the one on one was excellent!</p><hr> 
      <p class="name">A quick note to let you know that I am closing out the best two week stretch in my long trading career, and the credit goes to you. Your market sense and insight kept me on the right side of the market and in numerous successful trades.  My biggest obstacle in trading has always been being torn between my long term …</p><hr> 
      <p class="name">I will have to say, when I signed up for the room I thought the cost was perhaps a bit more than I wanted to pay.  Hmmm, have paid for several years worth in a couple of weeks by paying attention to JP. Thx. Randy E.</p><hr> 
      <p class="name">Mr John Person, I want to thank you for what has been for me the best trading room I have ever experienced. After trading every summer for 16 years my wife has finally convinced me to sell in May and go away. I’m not sure how it will go since I’m a day trader and like the excitement. I would …</p><hr> 
      <p class="name">Hi John, I picked this off of a buy signal a few weeks ago. I checked out fundamentally and it is interesting. THANKS!!!! for your indicators!. I have exited 2/3 of my position over 5.25 this morning. Take care of a few bills! – Thanks again! All my best</p><hr> 
      <p class="name">We’ve met several times at jeffrey’s meeting and I came to your seminar last fall. I ordered Tradestation and your indicators after that meeting. For a year I’ve had been in a job that kept me from looking at market intraday. I took a few weeks off between jobs and tried a little day trading. I’m not completely fluent on …</p><hr> 
      <p class="name">I always knew that the Person PPS and Doji signals were powerful but adding the Algo Optimizer makes the package awesome. A lot of traders lack confidence and creating your own systems with the clarification of statistical analysis is the ideal solution for this problem. Keep doing what you’re doing, all the best.</p><hr> 
      <p class="name">Thank you, Mary for all of your help and support last week during the mentoring. Testimonial sent: The personal mentoring with John Person is by far the best trading training I have experienced in 20 years! John adapted the training to suit my personal requests, and he more than fulfilled my expectations. From learning about his proprietary indicators (and receiving …</p><hr> 
    </ul>
    <ul class="pagination"></ul>
  </div>

  <script>
      var monkeyList = new List('test-list', {
  valueNames: ['name'],
  page: 18,
  pagination: true
});
      </script>
